import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageDir = path.resolve(__dirname, '..');
const sourceDir = path.join(packageDir, 'src/lib/iconsets');
const libDir = path.join(packageDir, 'src/lib');
const lockPath = path.join(packageDir, '.generate-icons.lock');

const generatedHeader = '// Generated by scripts/generate-icons.js. Do not edit by hand.\n';
const hardcodedCurrentColorCandidates = [
	'#000',
	'#000000',
	'#0f172a',
	'#111',
	'#111111',
	'#1f2937',
	'black',
	'rgb(0,0,0)',
	'rgb(0, 0, 0)'
];

function toIdentifierPart(value) {
	return value
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
}

function toNamedExport(setName, iconName) {
	const name = `${setName}-${iconName}`;
	const identifier = name.charAt(0).toLowerCase() + toIdentifierPart(name).slice(1);

	return /^[0-9]/.test(identifier) ? `icon${identifier}` : identifier;
}

function toSafePathName(filename) {
	return filename.replace(/\.svg$/i, '').toLowerCase();
}

function extractViewBox(svg) {
	return svg.match(/<svg[^>]*\bviewBox="([^"]+)"/i)?.[1] ?? '0 0 24 24';
}

function stripSvg(svg) {
	const inner = svg
		.replace(/<svg[^>]*>/i, '')
		.replace(/<\/svg>/i, '')
		.replace(/<rect[^>]*fill="none"[^>]*\/>\s*/gi, '')
		.replace(/<rect[^>]*fill="none"[^>]*><\/rect>\s*/gi, '')
		.trim();

	return normalizeColor(inner);
}

function normalizeColor(svg) {
	let result = svg;

	for (const color of hardcodedCurrentColorCandidates) {
		result = result
			.replaceAll(`fill="${color}"`, 'fill="currentColor"')
			.replaceAll(`stroke="${color}"`, 'stroke="currentColor"')
			.replaceAll(`fill:${color}`, 'fill:currentColor')
			.replaceAll(`stroke:${color}`, 'stroke:currentColor');
	}

	return result;
}

function cleanGeneratedSet(setName) {
	const setDir = path.join(libDir, setName);
	const setBarrel = path.join(libDir, `${setName}.ts`);

	fs.rmSync(setDir, { recursive: true, force: true });
	fs.rmSync(setBarrel, { force: true });
}

function writeIconModule(setName, iconName, svg) {
	const setDir = path.join(libDir, setName);
	const modulePath = path.join(setDir, `${iconName}.ts`);
	const exportName = toNamedExport(setName, iconName);
	const viewBox = extractViewBox(svg);
	const body = stripSvg(svg);

	fs.mkdirSync(setDir, { recursive: true });
	fs.writeFileSync(
		modulePath,
		`${generatedHeader}import type { IconData } from '../types.js';\n\nconst ${exportName} = ${JSON.stringify(
			{
				name: iconName,
				set: setName,
				viewBox,
				body
			},
			null,
			'\t'
		)} as const satisfies IconData;\n\nexport default ${exportName};\nexport { ${exportName} };\n`,
		'utf8'
	);

	return { exportName, iconName };
}

function writeSetBarrel(setName, icons) {
	const lines = icons.map(
		({ exportName, iconName }) => `export { default as ${exportName} } from './${setName}/${iconName}.js';`
	);

	fs.writeFileSync(path.join(libDir, `${setName}.ts`), `${generatedHeader}${lines.join('\n')}\n`, 'utf8');
}

if (!fs.existsSync(sourceDir)) {
	console.log('No iconsets directory found.');
	process.exit(0);
}

try {
	fs.writeFileSync(lockPath, String(process.pid), { flag: 'wx' });
} catch {
	console.error('Icon generation is already running.');
	process.exit(1);
}

const setNames = fs
	.readdirSync(sourceDir, { withFileTypes: true })
	.filter((entry) => entry.isDirectory())
	.map((entry) => entry.name)
	.sort();

try {
	for (const setName of setNames) {
		const setSourceDir = path.join(sourceDir, setName);
		const svgFiles = fs
			.readdirSync(setSourceDir, { withFileTypes: true })
			.filter((entry) => entry.isFile() && entry.name.endsWith('.svg'))
			.map((entry) => entry.name)
			.sort();

		cleanGeneratedSet(setName);

		const icons = svgFiles.map((file) => {
			const iconName = toSafePathName(file);
			const svg = fs.readFileSync(path.join(setSourceDir, file), 'utf8');

			return writeIconModule(setName, iconName, svg);
		});

		writeSetBarrel(setName, icons);
		console.log(`${setName}: generated ${icons.length} icons`);
	}
} finally {
	fs.rmSync(lockPath, { force: true });
}
