import { defineDocsConfig } from '@docs-kit/core';

export default defineDocsConfig({
	site: {
		title: "Standalone Docs",
		description: "Generated by @docs-kit/create."
	},
	content: { directory: "src/lib/docs" },
	routing: { basePath: "/docs" }
});
