export const exampleSources = {
	button: `<script lang="ts">\n\timport { Button } from '@fractaldesign/fractal-svelte/button';\n<\/script>\n\n<Button>Continue</Button>\n<Button variant="secondary">Save draft</Button>\n<Button variant="outline">Cancel</Button>`,
	tabs: `<script lang="ts">\n\timport { Tabs } from '@fractaldesign/fractal-svelte/tabs';\n\n\tconst items = [\n\t\t{ id: 'overview', label: 'Overview' },\n\t\t{ id: 'activity', label: 'Activity' },\n\t\t{ id: 'settings', label: 'Settings' }\n\t];\n\tlet activeId = $state('overview');\n<\/script>\n\n<Tabs tabs={items} bind:activeId variant="segment" />`,
	'message-bubble': `<script lang="ts">\n\timport { Message, MessageBubble, MessageBubbleContent } from '@fractaldesign/fractal-svelte/message-bubble';\n<\/script>\n\n<Message from="assistant"><MessageBubble><MessageBubbleContent>Here is your project update.</MessageBubbleContent></MessageBubble></Message>`,
	message: `<script lang="ts">\n\timport { Message, MessageContent } from '@fractaldesign/fractal-svelte/message';\n<\/script>\n\n<Message from="assistant"><MessageContent>Your deployment is ready for review.</MessageContent></Message>`,
	'message-scroller': `<script lang="ts">\n\timport { MessageScroller } from '@fractaldesign/fractal-svelte/message-scroller';\n<\/script>\n\n<MessageScroller label="Conversation"> <p>Conversation history</p> </MessageScroller>`,
	'prompt-input': `<script lang="ts">\n\timport { PromptInput } from '@fractaldesign/fractal-svelte/prompt-input';\n<\/script>\n\n<PromptInput onSubmit={(value) => console.log(value)} placeholder="Ask the agent" />`,
	'todo-list': `<script lang="ts">\n\timport { TodoList } from '@fractaldesign/fractal-svelte/todo-list';\n\n\tconst items = [{ id: 'plan', title: 'Make a plan', status: 'completed' }];\n<\/script>\n\n<TodoList {items} />`,
	'approval-card': `<script lang="ts">\n\timport { ApprovalCard } from '@fractaldesign/fractal-svelte/approval-card';\n<\/script>\n\n<ApprovalCard title="Publish changes?" onApprove={() => undefined} />`,
	'file-diff': `<script lang="ts">\n\timport { FileDiff } from '@fractaldesign/fractal-svelte/file-diff';\n\n\tconst lines = [{ id: '1', type: 'added', newLine: 1, content: 'const ready = true;' }];\n<\/script>\n\n<FileDiff file="src/status.ts" {lines} status="complete" />`,
	'streaming-response': `<script lang="ts">\n\timport { StreamingResponse } from '@fractaldesign/fractal-svelte/streaming-response';\n<\/script>\n\n<StreamingResponse status="complete"><p>The response is ready.</p></StreamingResponse>`,
	'ai-sidebar': `<script lang="ts">\n\timport { AiSidebar } from '@fractaldesign/fractal-svelte/ai-sidebar';\n\n\tconst items = [{ id: 'brief', label: 'Brief.md', kind: 'file' }];\n<\/script>\n\n<AiSidebar defaultItems={items} ariaLabel="Project resources" />`,
	'notification-stack': `<script lang="ts">\n\timport { NotificationStack } from '@fractaldesign/fractal-svelte/notification-stack';\n\n\tconst items = [{ id: 'release', title: 'Release ready', description: 'Version 2.4 is ready to review.' }];\n<\/script>\n\n<NotificationStack {items} />`,
	'expandable-action-bar': `<script lang="ts">\n\timport { ExpandableActionBar } from '@fractaldesign/fractal-svelte/expandable-action-bar';\n<\/script>\n\n<ExpandableActionBar items={items} />`,
	'overflow-actions': `<script lang="ts">\n\timport { OverflowActions } from '@fractaldesign/fractal-svelte/overflow-actions';\n<\/script>\n\n<OverflowActions items={items} label="More item actions" />`,
	'feedback-widget': `<script lang="ts">\n\timport { FeedbackWidget } from '@fractaldesign/fractal-svelte/feedback-widget';\n<\/script>\n\n<FeedbackWidget title="Share feedback" />`,
	'not-found': `<script lang="ts">\n\timport { NotFound } from '@fractaldesign/fractal-svelte/not-found';\n<\/script>\n\n<NotFound variant="spotlight" title="This view is unavailable" />`
} as const;
