// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorAlignBottom = {
	"name": "align-bottom",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"216\" y1=\"216\" x2=\"40\" y2=\"216\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorAlignBottom;
export { phosphorAlignBottom };
