// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorAndroidLogo = {
	"name": "android-logo",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"164\" cy=\"148\" r=\"12\"/><circle cx=\"92\" cy=\"148\" r=\"12\"/><path d=\"M24,184V161.13C24,103.65,70.15,56.2,127.63,56A104,104,0,0,1,232,160v24a8,8,0,0,1-8,8H32A8,8,0,0,1,24,184Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"32\" y1=\"48\" x2=\"63.07\" y2=\"79.07\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"224\" y1=\"48\" x2=\"193.1\" y2=\"78.9\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorAndroidLogo;
export { phosphorAndroidLogo };
