// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorAppWindow = {
	"name": "app-window",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"68\" cy=\"84\" r=\"12\"/><circle cx=\"108\" cy=\"84\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorAppWindow;
export { phosphorAppWindow };
