// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorApproximateEquals = {
	"name": "approximate-equals",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M40,161.61c72-59.69,104,56.47,176-3.22\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M40,97.61c72-59.69,104,56.47,176-3.22\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorApproximateEquals;
export { phosphorApproximateEquals };
