// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArchive = {
	"name": "archive",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M216,96v96a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"104\" y1=\"136\" x2=\"152\" y2=\"136\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArchive;
export { phosphorArchive };
