// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowBendLeftUp = {
	"name": "arrow-bend-left-up",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"152 80 104 32 56 80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M200,224a96,96,0,0,1-96-96V32\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowBendLeftUp;
export { phosphorArrowBendLeftUp };
