// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowFatDown = {
	"name": "arrow-fat-down",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M32,136l96,96,96-96H176V48a8,8,0,0,0-8-8H88a8,8,0,0,0-8,8v88Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowFatDown;
export { phosphorArrowFatDown };
