// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowDownLeft = {
	"name": "arrow-down-left",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"192\" y1=\"64\" x2=\"64\" y2=\"192\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"168 192 64 192 64 88\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowDownLeft;
export { phosphorArrowDownLeft };
