// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowBendDownLeft = {
	"name": "arrow-bend-down-left",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"80 104 32 152 80 200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M224,56a96,96,0,0,1-96,96H32\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowBendDownLeft;
export { phosphorArrowBendDownLeft };
