// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowDownRight = {
	"name": "arrow-down-right",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"64\" y1=\"64\" x2=\"192\" y2=\"192\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"88 192 192 192 192 88\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowDownRight;
export { phosphorArrowDownRight };
