// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowClockwise = {
	"name": "arrow-clockwise",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"184 104 232 104 232 56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M188.4,192a88,88,0,1,1,1.83-126.23L232,104\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowClockwise;
export { phosphorArrowClockwise };
