// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowURightDown = {
	"name": "arrow-u-right-down",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"120 176 168 224 216 176\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M56,176V88a56,56,0,0,1,56-56h0a56,56,0,0,1,56,56V224\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowURightDown;
export { phosphorArrowURightDown };
