// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowCounterClockwise = {
	"name": "arrow-counter-clockwise",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"24 56 24 104 72 104\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M67.59,192A88,88,0,1,0,65.77,65.77L24,104\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowCounterClockwise;
export { phosphorArrowCounterClockwise };
