// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowSquareDownRight = {
	"name": "arrow-square-down-right",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"160\" y1=\"160\" x2=\"96\" y2=\"96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"160 112 160 160 112 160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowSquareDownRight;
export { phosphorArrowSquareDownRight };
