// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowElbowRight = {
	"name": "arrow-elbow-right",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"160 80 232 80 232 152\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"24 96 120 192 232 80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowElbowRight;
export { phosphorArrowElbowRight };
