// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowSquareUpLeft = {
	"name": "arrow-square-up-left",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"144 96 96 96 96 144\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"160\" y1=\"160\" x2=\"96\" y2=\"96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowSquareUpLeft;
export { phosphorArrowSquareUpLeft };
