// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowUUpRight = {
	"name": "arrow-u-up-right",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"176 136 224 88 176 40\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M176,200H88a56,56,0,0,1-56-56h0A56,56,0,0,1,88,88H224\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowUUpRight;
export { phosphorArrowUUpRight };
