// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowFatLeft = {
	"name": "arrow-fat-left",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M120,32,24,128l96,96V176h88a8,8,0,0,0,8-8V88a8,8,0,0,0-8-8H120Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowFatLeft;
export { phosphorArrowFatLeft };
