// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowBendDownRight = {
	"name": "arrow-bend-down-right",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"176 104 224 152 176 200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M32,56a96,96,0,0,0,96,96h96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowBendDownRight;
export { phosphorArrowBendDownRight };
