// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowULeftUp = {
	"name": "arrow-u-left-up",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"136 80 88 32 40 80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M200,80v88a56,56,0,0,1-56,56h0a56,56,0,0,1-56-56V32\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowULeftUp;
export { phosphorArrowULeftUp };
