// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowElbowLeft = {
	"name": "arrow-elbow-left",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"96 80 24 80 24 152\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"232 96 136 192 24 80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowElbowLeft;
export { phosphorArrowElbowLeft };
