// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowSquareDownLeft = {
	"name": "arrow-square-down-left",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"96 112 96 160 144 160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"160\" y1=\"96\" x2=\"96\" y2=\"160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowSquareDownLeft;
export { phosphorArrowSquareDownLeft };
