// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowBendUpRight = {
	"name": "arrow-bend-up-right",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"176 152 224 104 176 56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M32,200a96,96,0,0,1,96-96h96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowBendUpRight;
export { phosphorArrowBendUpRight };
