// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowFatLineUp = {
	"name": "arrow-fat-line-up",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polygon points=\"32 120 128 24 224 120 176 120 176 184 80 184 80 120 32 120\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"176\" y1=\"216\" x2=\"80\" y2=\"216\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowFatLineUp;
export { phosphorArrowFatLineUp };
