// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorArrowULeftDown = {
	"name": "arrow-u-left-down",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"136 176 88 224 40 176\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M200,176V88a56,56,0,0,0-56-56h0A56,56,0,0,0,88,88V224\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorArrowULeftDown;
export { phosphorArrowULeftDown };
