// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBathtub = {
	"name": "bathtub",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"72\" y1=\"192\" x2=\"72\" y2=\"216\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"184\" y1=\"192\" x2=\"184\" y2=\"216\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M200,104h40v40a48,48,0,0,1-48,48H64a48,48,0,0,1-48-48V104H136\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M56,104V52A20,20,0,0,1,76,32,20.44,20.44,0,0,1,96,48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorBathtub;
export { phosphorBathtub };
