// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBatteryWarning = {
	"name": "battery-warning",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"248\" y1=\"96\" x2=\"248\" y2=\"160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"116\" y1=\"96\" x2=\"116\" y2=\"124\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"116\" cy=\"156\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorBatteryWarning;
export { phosphorBatteryWarning };
