// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBatteryWarningVertical = {
	"name": "battery-warning-vertical",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"128\" y1=\"96\" x2=\"128\" y2=\"136\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"128\" cy=\"172\" r=\"12\"/><line x1=\"96\" y1=\"8\" x2=\"160\" y2=\"8\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorBatteryWarningVertical;
export { phosphorBatteryWarningVertical };
