// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBatteryChargingVertical = {
	"name": "battery-charging-vertical",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"128 168 144 136 112 136 128 104\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"96\" y1=\"8\" x2=\"160\" y2=\"8\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorBatteryChargingVertical;
export { phosphorBatteryChargingVertical };
