// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBluetoothConnected = {
	"name": "bluetooth-connected",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polygon points=\"128 32 192 80 128 128 128 32\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polygon points=\"128 128 192 176 128 224 128 128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"64\" y1=\"80\" x2=\"128\" y2=\"128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"64\" y1=\"176\" x2=\"128\" y2=\"128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"60\" cy=\"128\" r=\"12\"/><circle cx=\"204\" cy=\"128\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorBluetoothConnected;
export { phosphorBluetoothConnected };
