// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBookOpen = {
	"name": "book-open",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M128,88a32,32,0,0,1,32-32h72V200H160a32,32,0,0,0-32,32\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M24,200H96a32,32,0,0,1,32,32V88A32,32,0,0,0,96,56H24Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorBookOpen;
export { phosphorBookOpen };
