// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBoules = {
	"name": "boules",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"167.52\" y1=\"40.48\" x2=\"40.48\" y2=\"167.52\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"195.88\" y1=\"60.12\" x2=\"60.12\" y2=\"195.88\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"215.52\" y1=\"88.48\" x2=\"88.48\" y2=\"215.52\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorBoules;
export { phosphorBoules };
