// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBowlingBall = {
	"name": "bowling-ball",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"132\" cy=\"116\" r=\"12\"/><circle cx=\"164\" cy=\"92\" r=\"12\"/><circle cx=\"172\" cy=\"132\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorBowlingBall;
export { phosphorBowlingBall };
