// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBracketsRound = {
	"name": "brackets-round",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M72,40S32,64,32,128s40,88,40,88\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M184,40s40,24,40,88-40,88-40,88\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorBracketsRound;
export { phosphorBracketsRound };
