// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorBugDroid = {
	"name": "bug-droid",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M48,112a80,80,0,0,1,160,0v40a80,80,0,0,1-160,0Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"208\" y1=\"128\" x2=\"48\" y2=\"128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"156\" cy=\"92\" r=\"12\"/><circle cx=\"100\" cy=\"92\" r=\"12\"/><line x1=\"200\" y1=\"32\" x2=\"180.43\" y2=\"51.57\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"56\" y1=\"32\" x2=\"75.57\" y2=\"51.57\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorBugDroid;
export { phosphorBugDroid };
