// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCalendarDots = {
	"name": "calendar-dots",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"176\" y1=\"24\" x2=\"176\" y2=\"56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"80\" y1=\"24\" x2=\"80\" y2=\"56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"40\" y1=\"88\" x2=\"216\" y2=\"88\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"128\" cy=\"132\" r=\"12\"/><circle cx=\"172\" cy=\"132\" r=\"12\"/><circle cx=\"84\" cy=\"172\" r=\"12\"/><circle cx=\"128\" cy=\"172\" r=\"12\"/><circle cx=\"172\" cy=\"172\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorCalendarDots;
export { phosphorCalendarDots };
