// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCardholder = {
	"name": "cardholder",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M32,120H96a32,32,0,0,0,64,0h64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"32\" y1=\"88\" x2=\"224\" y2=\"88\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCardholder;
export { phosphorCardholder };
