// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCards = {
	"name": "cards",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M64,48H216a8,8,0,0,1,8,8V176\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCards;
export { phosphorCards };
