// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCaretDown = {
	"name": "caret-down",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"208 96 128 176 48 96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCaretDown;
export { phosphorCaretDown };
