// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCaretUpDown = {
	"name": "caret-up-down",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"80 176 128 224 176 176\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"80 80 128 32 176 80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCaretUpDown;
export { phosphorCaretUpDown };
