// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCaretLineDown = {
	"name": "caret-line-down",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"208 72 128 152 48 72\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"48\" y1=\"192\" x2=\"208\" y2=\"192\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCaretLineDown;
export { phosphorCaretLineDown };
