// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCaretLineLeft = {
	"name": "caret-line-left",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"192 208 112 128 192 48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"72\" y1=\"48\" x2=\"72\" y2=\"208\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCaretLineLeft;
export { phosphorCaretLineLeft };
