// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorChalkboard = {
	"name": "chalkboard",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M32,200V56a8,8,0,0,1,8-8H216a8,8,0,0,1,8,8V200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"16\" y1=\"200\" x2=\"240\" y2=\"200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"120 200 120 168 192 168 192 200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"64 200 64 80 192 80 192 136\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorChalkboard;
export { phosphorChalkboard };
