// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorChalkboardSimple = {
	"name": "chalkboard-simple",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M32,200V56a8,8,0,0,1,8-8H216a8,8,0,0,1,8,8v80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"16\" y1=\"200\" x2=\"240\" y2=\"200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"160 200 160 168 224 168 224 200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorChalkboardSimple;
export { phosphorChalkboardSimple };
