// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorChartScatter = {
	"name": "chart-scatter",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"224 208 32 208 32 48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"132\" cy=\"148\" r=\"12\"/><circle cx=\"108\" cy=\"92\" r=\"12\"/><circle cx=\"76\" cy=\"164\" r=\"12\"/><circle cx=\"172\" cy=\"116\" r=\"12\"/><circle cx=\"196\" cy=\"76\" r=\"12\"/><circle cx=\"188\" cy=\"164\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorChartScatter;
export { phosphorChartScatter };
