// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorChartPieSlice = {
	"name": "chart-pie-slice",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M33.6,145.5A96,96,0,0,1,96,37.5v72Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M128,128.42V32A96,96,0,1,1,45.22,176.64Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorChartPieSlice;
export { phosphorChartPieSlice };
