// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorChartLine = {
	"name": "chart-line",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"224 208 32 208 32 48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"224 96 160 152 96 104 32 160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorChartLine;
export { phosphorChartLine };
