// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorChatTeardropDots = {
	"name": "chat-teardrop-dots",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M132,216H48a8,8,0,0,1-8-8V124a92,92,0,0,1,92-92h0a92,92,0,0,1,92,92h0A92,92,0,0,1,132,216Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"132\" cy=\"128\" r=\"12\"/><circle cx=\"88\" cy=\"128\" r=\"12\"/><circle cx=\"176\" cy=\"128\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorChatTeardropDots;
export { phosphorChatTeardropDots };
