// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorChecks = {
	"name": "checks",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"16 130.29 54.4 168 144 80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"125.96 144 150.4 168 240 80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorChecks;
export { phosphorChecks };
