// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorClockCounterClockwise = {
	"name": "clock-counter-clockwise",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"128 80 128 128 168 152\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"72 104 32 104 32 64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M67.6,192A88,88,0,1,0,65.77,65.77C54,77.69,44.28,88.93,32,104\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorClockCounterClockwise;
export { phosphorClockCounterClockwise };
