// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorClockClockwise = {
	"name": "clock-clockwise",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"128 80 128 128 168 152\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"184 104 224 104 224 64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M188.4,192a88,88,0,1,1,1.83-126.23C202,77.69,211.72,88.93,224,104\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorClockClockwise;
export { phosphorClockClockwise };
