// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCloudLightning = {
	"name": "cloud-lightning",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M88,88a68.06,68.06,0,1,1,68,72H76A44,44,0,1,1,90.2,74.34\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"120 240 144 200 104 200 128 160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCloudLightning;
export { phosphorCloudLightning };
