// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCodeSimple = {
	"name": "code-simple",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"88 64 16 128 88 192\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"168 64 240 128 168 192\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCodeSimple;
export { phosphorCodeSimple };
