// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorColumnsPlusLeft = {
	"name": "columns-plus-left",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"16\" y1=\"128\" x2=\"64\" y2=\"128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"40\" y1=\"104\" x2=\"40\" y2=\"152\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorColumnsPlusLeft;
export { phosphorColumnsPlusLeft };
