// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorControl = {
	"name": "control",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"56 120 128 48 200 120\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorControl;
export { phosphorControl };
