// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCookie = {
	"name": "cookie",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"156\" cy=\"172\" r=\"12\"/><circle cx=\"92\" cy=\"164\" r=\"12\"/><circle cx=\"84\" cy=\"108\" r=\"12\"/><circle cx=\"132\" cy=\"124\" r=\"12\"/><path d=\"M224,128a48,48,0,0,1-48-48,48,48,0,0,1-48-48,96,96,0,1,0,96,96Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCookie;
export { phosphorCookie };
