// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCurrencyRub = {
	"name": "currency-rub",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"56\" y1=\"176\" x2=\"144\" y2=\"176\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M88,216V40h60a52,52,0,0,1,0,104H56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCurrencyRub;
export { phosphorCurrencyRub };
