// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCurrencyKrw = {
	"name": "currency-krw",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"24 72 76 200 128 72 180 200 232 72\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"16\" y1=\"136\" x2=\"240\" y2=\"136\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCurrencyKrw;
export { phosphorCurrencyKrw };
