// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorCurrencyEur = {
	"name": "currency-eur",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"40\" y1=\"112\" x2=\"136\" y2=\"112\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"40\" y1=\"144\" x2=\"120\" y2=\"144\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M184,197.67A72,72,0,0,1,64,144V112A72,72,0,0,1,184,58.33\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorCurrencyEur;
export { phosphorCurrencyEur };
