// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDatabase = {
	"name": "database",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<ellipse cx=\"128\" cy=\"80\" rx=\"88\" ry=\"48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M40,80v48c0,26.51,39.4,48,88,48s88-21.49,88-48V80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M40,128v48c0,26.51,39.4,48,88,48s88-21.49,88-48V128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorDatabase;
export { phosphorDatabase };
