// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDeviceMobile = {
	"name": "device-mobile",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"64\" y1=\"56\" x2=\"192\" y2=\"56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"64\" y1=\"200\" x2=\"192\" y2=\"200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorDeviceMobile;
export { phosphorDeviceMobile };
