// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDeviceTabletCamera = {
	"name": "device-tablet-camera",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"68\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorDeviceTabletCamera;
export { phosphorDeviceTabletCamera };
