// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDeviceTabletSpeaker = {
	"name": "device-tablet-speaker",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"96\" y1=\"64\" x2=\"160\" y2=\"64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorDeviceTabletSpeaker;
export { phosphorDeviceTabletSpeaker };
