// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDiceThree = {
	"name": "dice-three",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"92\" cy=\"92\" r=\"12\"/><circle cx=\"128\" cy=\"128\" r=\"12\"/><circle cx=\"164\" cy=\"164\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorDiceThree;
export { phosphorDiceThree };
