// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDiceFour = {
	"name": "dice-four",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"100\" cy=\"100\" r=\"12\"/><circle cx=\"156\" cy=\"100\" r=\"12\"/><circle cx=\"100\" cy=\"156\" r=\"12\"/><circle cx=\"156\" cy=\"156\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorDiceFour;
export { phosphorDiceFour };
