// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDiceSix = {
	"name": "dice-six",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"92\" cy=\"84\" r=\"12\"/><circle cx=\"164\" cy=\"84\" r=\"12\"/><circle cx=\"92\" cy=\"128\" r=\"12\"/><circle cx=\"164\" cy=\"128\" r=\"12\"/><circle cx=\"92\" cy=\"172\" r=\"12\"/><circle cx=\"164\" cy=\"172\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorDiceSix;
export { phosphorDiceSix };
