// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDivide = {
	"name": "divide",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"40\" y1=\"128\" x2=\"216\" y2=\"128\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"128\" cy=\"64\" r=\"16\"/><circle cx=\"128\" cy=\"192\" r=\"16\"/>"
} as const satisfies IconData;

export default phosphorDivide;
export { phosphorDivide };
