// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDoorOpen = {
	"name": "door-open",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"24\" y1=\"224\" x2=\"232\" y2=\"224\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M56,224V40a8,8,0,0,1,8-8H192a8,8,0,0,1,8,8V224\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"132\" cy=\"132\" r=\"12\"/><line x1=\"168\" y1=\"32\" x2=\"168\" y2=\"224\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorDoorOpen;
export { phosphorDoorOpen };
