// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDotsSix = {
	"name": "dots-six",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"60\" cy=\"92\" r=\"12\"/><circle cx=\"128\" cy=\"92\" r=\"12\"/><circle cx=\"196\" cy=\"92\" r=\"12\"/><circle cx=\"60\" cy=\"164\" r=\"12\"/><circle cx=\"128\" cy=\"164\" r=\"12\"/><circle cx=\"196\" cy=\"164\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorDotsSix;
export { phosphorDotsSix };
