// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDotsThreeOutlineVertical = {
	"name": "dots-three-outline-vertical",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/><circle cx=\"128\" cy=\"48\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/><circle cx=\"128\" cy=\"208\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorDotsThreeOutlineVertical;
export { phosphorDotsThreeOutlineVertical };
