// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDotsThreeCircleVertical = {
	"name": "dots-three-circle-vertical",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"96\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/><circle cx=\"128\" cy=\"128\" r=\"12\"/><circle cx=\"128\" cy=\"84\" r=\"12\"/><circle cx=\"128\" cy=\"172\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorDotsThreeCircleVertical;
export { phosphorDotsThreeCircleVertical };
