// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDotsThreeVertical = {
	"name": "dots-three-vertical",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"12\"/><circle cx=\"128\" cy=\"60\" r=\"12\"/><circle cx=\"128\" cy=\"196\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorDotsThreeVertical;
export { phosphorDotsThreeVertical };
