// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDotsThree = {
	"name": "dots-three",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"12\"/><circle cx=\"196\" cy=\"128\" r=\"12\"/><circle cx=\"60\" cy=\"128\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorDotsThree;
export { phosphorDotsThree };
