// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDotsThreeOutline = {
	"name": "dots-three-outline",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/><circle cx=\"48\" cy=\"128\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/><circle cx=\"208\" cy=\"128\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorDotsThreeOutline;
export { phosphorDotsThreeOutline };
