// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorDresser = {
	"name": "dresser",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"136\" y1=\"192\" x2=\"120\" y2=\"192\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"136\" y1=\"64\" x2=\"120\" y2=\"64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"136\" y1=\"128\" x2=\"120\" y2=\"128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"48\" y1=\"96\" x2=\"208\" y2=\"96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"48\" y1=\"160\" x2=\"208\" y2=\"160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorDresser;
export { phosphorDresser };
