// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorEgg = {
	"name": "egg",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M208,152a80,80,0,0,1-160,0C48,88,96,24,128,24S208,88,208,152Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorEgg;
export { phosphorEgg };
