// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorFileCloud = {
	"name": "file-cloud",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"152 32 152 88 208 88\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M176,224h24a8,8,0,0,0,8-8V88L152,32H56a8,8,0,0,0-8,8v88\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M65.66,168H60a28,28,0,0,0,0,56h48a44,44,0,1,0-43.82-48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorFileCloud;
export { phosphorFileCloud };
