// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorFilmScript = {
	"name": "film-script",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"84\" cy=\"76\" r=\"12\"/><circle cx=\"84\" cy=\"180\" r=\"12\"/><circle cx=\"84\" cy=\"128\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorFilmScript;
export { phosphorFilmScript };
