// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorFinnTheHuman = {
	"name": "finn-the-human",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M24,72a24,24,0,0,1,48,0H184a24,24,0,0,1,48,0v80a64,64,0,0,1-64,64H88a64,64,0,0,1-64-64Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"92\" cy=\"148\" r=\"12\"/><circle cx=\"164\" cy=\"148\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorFinnTheHuman;
export { phosphorFinnTheHuman };
