// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorFlagBanner = {
	"name": "flag-banner",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"152 224 232 56 40 56 88 104 40 152 186.29 152\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorFlagBanner;
export { phosphorFlagBanner };
