// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorFlagBannerFold = {
	"name": "flag-banner-fold",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"152 224 232 48 152 48 112 136 192 136\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"112 136 101.09 160 28 160 68 116 28 72 141.09 72\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorFlagBannerFold;
export { phosphorFlagBannerFold };
