// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorFlame = {
	"name": "flame",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M208,144c0-72-80-120-80-120S48,72,48,144a80,80,0,0,0,160,0Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M88,184a40,40,0,0,0,80,0c0-40-40-64-40-64S88,144,88,184Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorFlame;
export { phosphorFlame };
