// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorFramerLogo = {
	"name": "framer-logo",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polygon points=\"56 104 56 168 128 240 128 168 200 168 56 40 200 40 200 104 56 104\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorFramerLogo;
export { phosphorFramerLogo };
