// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorGavel = {
	"name": "gavel",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"145.66\" y1=\"49.66\" x2=\"206.34\" y2=\"110.34\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"89.66\" y1=\"105.66\" x2=\"150.34\" y2=\"166.34\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M132,148,61,219a17,17,0,0,1-24,0h0a17,17,0,0,1,0-24l71-71\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorGavel;
export { phosphorGavel };
