// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorGoogleLogo = {
	"name": "google-logo",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M128,128h88a88,88,0,1,1-20.11-56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorGoogleLogo;
export { phosphorGoogleLogo };
