// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorGooglePhotosLogo = {
	"name": "google-photos-logo",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M128,128V24a64,64,0,0,1,50,104\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M128,128H24A64,64,0,0,1,128,78\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M128,128V232A64,64,0,0,1,78,128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M128,128H232a64,64,0,0,1-104,50\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorGooglePhotosLogo;
export { phosphorGooglePhotosLogo };
