// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorGreaterThanOrEqual = {
	"name": "greater-than-or-equal",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"56 48 208 104 56 160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"208\" y1=\"200\" x2=\"56\" y2=\"200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorGreaterThanOrEqual;
export { phosphorGreaterThanOrEqual };
