// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorGreaterThan = {
	"name": "greater-than",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"64 56 216 128 64 200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorGreaterThan;
export { phosphorGreaterThan };
