// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorHardHat = {
	"name": "hard-hat",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M104,160V40a8,8,0,0,1,8-8h32a8,8,0,0,1,8,8V160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M216,160V136a88,88,0,0,0-64-84.69\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M40,160V136a88,88,0,0,1,64-84.69\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorHardHat;
export { phosphorHardHat };
