// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorHardDrive = {
	"name": "hard-drive",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"188\" cy=\"128\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorHardDrive;
export { phosphorHardDrive };
