// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorImage = {
	"name": "image",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"156\" cy=\"100\" r=\"12\"/><path d=\"M147.31,164,173,138.34a8,8,0,0,1,11.31,0L224,178.06\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M32,168.69l54.34-54.35a8,8,0,0,1,11.32,0L191.31,208\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorImage;
export { phosphorImage };
