// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorInstagramLogo = {
	"name": "instagram-logo",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"40\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/><circle cx=\"180\" cy=\"76\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorInstagramLogo;
export { phosphorInstagramLogo };
