// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorIntersectThree = {
	"name": "intersect-three",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"92\" r=\"60\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"164\" cy=\"156\" r=\"60\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"92\" cy=\"156\" r=\"60\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorIntersectThree;
export { phosphorIntersectThree };
