// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorLasso = {
	"name": "lasso",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<ellipse cx=\"128\" cy=\"112\" rx=\"104\" ry=\"64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M48,225.6c32,16.7,80,0,80-41.77,0-53.66-60.64-62.5-70.62-24.85\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorLasso;
export { phosphorLasso };
