// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorLegoSmiley = {
	"name": "lego-smiley",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"100\" cy=\"112\" r=\"12\"/><circle cx=\"156\" cy=\"112\" r=\"12\"/><path d=\"M156,152a53,53,0,0,1-56,0\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M96,56V32a8,8,0,0,1,8-8h48a8,8,0,0,1,8,8V56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M72,200v24a8,8,0,0,0,8,8h96a8,8,0,0,0,8-8V200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorLegoSmiley;
export { phosphorLegoSmiley };
