// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorLightning = {
	"name": "lightning",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polygon points=\"160 16 144 96 208 120 96 240 112 160 48 136 160 16\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorLightning;
export { phosphorLightning };
