// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorLinkSimpleHorizontalBreak = {
	"name": "link-simple-horizontal-break",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M104,176H64a48,48,0,0,1,0-96h40\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M152,80h40a48,48,0,0,1,48,48h0a48,48,0,0,1-48,48H152\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorLinkSimpleHorizontalBreak;
export { phosphorLinkSimpleHorizontalBreak };
