// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorLockOpen = {
	"name": "lock-open",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"152\" r=\"12\"/><path d=\"M88,88V56a40,40,0,0,1,40-40c19.35,0,36.29,13.74,40,32\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorLockOpen;
export { phosphorLockOpen };
