// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorMapPinSimple = {
	"name": "map-pin-simple",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"72\" r=\"48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"128\" y1=\"232\" x2=\"128\" y2=\"120\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorMapPinSimple;
export { phosphorMapPinSimple };
