// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorMonitor = {
	"name": "monitor",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"160\" y1=\"224\" x2=\"96\" y2=\"224\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorMonitor;
export { phosphorMonitor };
