// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorNotSubsetOf = {
	"name": "not-subset-of",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"208\" y1=\"40\" x2=\"48\" y2=\"216\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M200,48H128a80,80,0,0,0-80,80h0a80,80,0,0,0,80,80h72\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorNotSubsetOf;
export { phosphorNotSubsetOf };
