// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorNumberTwo = {
	"name": "number-two",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M91.33,72a40,40,0,1,1,68.61,40.07L88,208h80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorNumberTwo;
export { phosphorNumberTwo };
