// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorNumberSquareFour = {
	"name": "number-square-four",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"160 152 88 152 144 80 144 176\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorNumberSquareFour;
export { phosphorNumberSquareFour };
