// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorNumberSquareTwo = {
	"name": "number-square-two",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M152,176H104l43.17-57.56A24,24,0,1,0,105.37,96\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorNumberSquareTwo;
export { phosphorNumberSquareTwo };
