// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorNumberSquareZero = {
	"name": "number-square-zero",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<ellipse cx=\"128\" cy=\"128\" rx=\"36\" ry=\"48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorNumberSquareZero;
export { phosphorNumberSquareZero };
