// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorNumberFive = {
	"name": "number-five",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M88,195.78a48,48,0,1,0,.92-72.36L104,48h64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorNumberFive;
export { phosphorNumberFive };
