// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorNumberSeven = {
	"name": "number-seven",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"88 48 168 48 120 208\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorNumberSeven;
export { phosphorNumberSeven };
