// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorNumberThree = {
	"name": "number-three",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M88,48h80l-48,64a48,48,0,1,1-32,83.78\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorNumberThree;
export { phosphorNumberThree };
