// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorNumpad = {
	"name": "numpad",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"64\" cy=\"48\" r=\"16\"/><circle cx=\"128\" cy=\"48\" r=\"16\"/><circle cx=\"192\" cy=\"48\" r=\"16\"/><circle cx=\"64\" cy=\"104\" r=\"16\"/><circle cx=\"128\" cy=\"104\" r=\"16\"/><circle cx=\"192\" cy=\"104\" r=\"16\"/><circle cx=\"64\" cy=\"160\" r=\"16\"/><circle cx=\"128\" cy=\"160\" r=\"16\"/><circle cx=\"128\" cy=\"216\" r=\"16\"/><circle cx=\"192\" cy=\"160\" r=\"16\"/>"
} as const satisfies IconData;

export default phosphorNumpad;
export { phosphorNumpad };
