// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorOven = {
	"name": "oven",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"84\" cy=\"76\" r=\"12\"/><circle cx=\"128\" cy=\"76\" r=\"12\"/><circle cx=\"172\" cy=\"76\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorOven;
export { phosphorOven };
