// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorPaperclipHorizontal = {
	"name": "paperclip-horizontal",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M80,144H192a16,16,0,0,0,0-32H48a32,32,0,0,0,0,64H192a48,48,0,0,0,0-96H80\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorPaperclipHorizontal;
export { phosphorPaperclipHorizontal };
