// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorPath = {
	"name": "path",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"200\" cy=\"200\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M72,56h96a32,32,0,0,1,0,64H72a40,40,0,0,0,0,80H176\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorPath;
export { phosphorPath };
