// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorPersonSimpleThrow = {
	"name": "person-simple-throw",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"56\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"64\" cy=\"96\" r=\"16\"/><path d=\"M216,105.6s-32-25.67-80,7c-50.47,34.3-80,20.85-80,20.85\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M143.89,107.62C143,126.17,144,208,64,232\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"139.94 145.95 176 176 160 224\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorPersonSimpleThrow;
export { phosphorPersonSimpleThrow };
