// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorPersonSimpleRun = {
	"name": "person-simple-run",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"152\" cy=\"56\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M56,105.6s32-25.67,80,7c50.47,34.3,80,20.85,80,20.85\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M110.64,161.16C128.47,165,176,180,176,232\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M134.44,111.51C128.37,135.24,98.81,206.68,32,200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorPersonSimpleRun;
export { phosphorPersonSimpleRun };
