// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorPersonSimpleSwim = {
	"name": "person-simple-swim",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"176\" cy=\"72\" r=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M40,193.61c72-59.69,104,56.47,176-3.22\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M40,153.61c72-59.69,104,56.47,176-3.22\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M189.58,165.58l-57.46-57.46A96,96,0,0,0,64.24,80H40\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"79.96\" y1=\"136.04\" x2=\"118.91\" y2=\"97.09\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorPersonSimpleSwim;
export { phosphorPersonSimpleSwim };
