// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorPictureInPicture = {
	"name": "picture-in-picture",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"136 200 136 128 224 128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorPictureInPicture;
export { phosphorPictureInPicture };
