// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorPlaceholder = {
	"name": "placeholder",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"42.34\" y1=\"42.34\" x2=\"213.66\" y2=\"213.66\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorPlaceholder;
export { phosphorPlaceholder };
