// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorProhibit = {
	"name": "prohibit",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"195.88\" y1=\"195.88\" x2=\"60.12\" y2=\"60.12\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"128\" cy=\"128\" r=\"96\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorProhibit;
export { phosphorProhibit };
