// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorPulse = {
	"name": "pulse",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"24 128 56 128 96 40 160 208 200 128 232 128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorPulse;
export { phosphorPulse };
