// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorRowsPlusTop = {
	"name": "rows-plus-top",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"104\" y1=\"40\" x2=\"152\" y2=\"40\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"128\" y1=\"16\" x2=\"128\" y2=\"64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorRowsPlusTop;
export { phosphorRowsPlusTop };
