// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorScribbleLoop = {
	"name": "scribble-loop",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M32,92.8S64,48,112,48c104,0,92.6,160-3.4,160-64,0-64-96,32-96,64,0,107.4,48,107.4,48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorScribbleLoop;
export { phosphorScribbleLoop };
