// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorShower = {
	"name": "shower",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"52\" cy=\"236\" r=\"12\"/><circle cx=\"84\" cy=\"204\" r=\"12\"/><circle cx=\"20\" cy=\"204\" r=\"12\"/><circle cx=\"52\" cy=\"172\" r=\"12\"/><path d=\"M248,40H216L184,72,161.91,201.31a8,8,0,0,1-13.54,4.34l-98-98a8,8,0,0,1,4.34-13.54L184,72\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorShower;
export { phosphorShower };
