// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSigma = {
	"name": "sigma",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"192 72 192 48 64 48 128 128 64 208 192 208 192 184\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorSigma;
export { phosphorSigma };
