// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSmileySad = {
	"name": "smiley-sad",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"96\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/><circle cx=\"92\" cy=\"108\" r=\"12\"/><circle cx=\"164\" cy=\"108\" r=\"12\"/><path d=\"M168,176c-8.3-14.35-22.23-24-40-24s-31.7,9.65-40,24\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorSmileySad;
export { phosphorSmileySad };
