// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSmileyNervous = {
	"name": "smiley-nervous",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"128\" cy=\"128\" r=\"96\" fill=\"none\" stroke=\"currentColor\" stroke-miterlimit=\"10\" stroke-width=\"16\"/><circle cx=\"92\" cy=\"108\" r=\"12\"/><circle cx=\"164\" cy=\"108\" r=\"12\"/><path d=\"M80,168c12,0,12-16,24-16s12,16,24,16,12-16,24-16,12,16,24,16\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorSmileyNervous;
export { phosphorSmileyNervous };
