// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSmileySticker = {
	"name": "smiley-sticker",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M168,152c-8.3,14.35-22.23,24-40,24s-31.7-9.65-40-24\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M156.22,219.79a95.9,95.9,0,1,1,63.57-63.58Z\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"92\" cy=\"108\" r=\"12\"/><circle cx=\"164\" cy=\"108\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorSmileySticker;
export { phosphorSmileySticker };
