// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSquareLogo = {
	"name": "square-logo",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": ""
} as const satisfies IconData;

export default phosphorSquareLogo;
export { phosphorSquareLogo };
