// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSquaresFour = {
	"name": "squares-four",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": ""
} as const satisfies IconData;

export default phosphorSquaresFour;
export { phosphorSquaresFour };
