// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSquareSplitVertical = {
	"name": "square-split-vertical",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"48\" y1=\"128\" x2=\"208\" y2=\"128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorSquareSplitVertical;
export { phosphorSquareSplitVertical };
