// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorStackSimple = {
	"name": "stack-simple",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polygon points=\"16 104 128 168 240 104 128 40 16 104\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"16 144 128 208 240 144\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorStackSimple;
export { phosphorStackSimple };
