// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorStarOfDavid = {
	"name": "star-of-david",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polygon points=\"128 240 224 72 32 72.04 128 240\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polygon points=\"128 16 224 184 32 183.96 128 16\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorStarOfDavid;
export { phosphorStarOfDavid };
