// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSteps = {
	"name": "steps",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"16 200 72 200 72 152 128 152 128 104 184 104 184 56 240 56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorSteps;
export { phosphorSteps };
