// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSuitcase = {
	"name": "suitcase",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M168,208V48a16,16,0,0,0-16-16H104A16,16,0,0,0,88,48V208\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorSuitcase;
export { phosphorSuitcase };
