// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSupersetProperOf = {
	"name": "superset-proper-of",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M64,208h72a80,80,0,0,0,0-160H64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorSupersetProperOf;
export { phosphorSupersetProperOf };
