// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorSupersetOf = {
	"name": "superset-of",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"208\" y1=\"200\" x2=\"56\" y2=\"200\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M56,48h96a56,56,0,0,1,0,112H56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorSupersetOf;
export { phosphorSupersetOf };
