// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTelevisionSimple = {
	"name": "television-simple",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"80 24 128 72 176 24\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorTelevisionSimple;
export { phosphorTelevisionSimple };
