// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTent = {
	"name": "tent",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polygon points=\"72 48 8 192 136 192 72 48\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"136 192 248 192 184 48 72 48 72 192\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorTent;
export { phosphorTent };
