// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTerminalWindow = {
	"name": "terminal-window",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"80 96 120 128 80 160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"136\" y1=\"160\" x2=\"176\" y2=\"160\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorTerminalWindow;
export { phosphorTerminalWindow };
