// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTerminal = {
	"name": "terminal",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"40 64 112 128 40 192\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"120\" y1=\"192\" x2=\"216\" y2=\"192\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorTerminal;
export { phosphorTerminal };
