// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTextB = {
	"name": "text-b",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M80,120h80a40,40,0,0,1,0,80H80V48h68a36,36,0,0,1,0,72\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorTextB;
export { phosphorTextB };
