// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorToggleRight = {
	"name": "toggle-right",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"176\" cy=\"128\" r=\"32\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorToggleRight;
export { phosphorToggleRight };
