// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTrafficSign = {
	"name": "traffic-sign",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M88,152v-8a24,24,0,0,1,24-24h56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"144 96 168 120 144 144\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorTrafficSign;
export { phosphorTrafficSign };
