// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTrainSimple = {
	"name": "train-simple",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"96\" y1=\"208\" x2=\"72\" y2=\"240\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"160\" y1=\"208\" x2=\"184\" y2=\"240\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"48\" y1=\"128\" x2=\"208\" y2=\"128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><circle cx=\"84\" cy=\"172\" r=\"12\"/><circle cx=\"172\" cy=\"172\" r=\"12\"/>"
} as const satisfies IconData;

export default phosphorTrainSimple;
export { phosphorTrainSimple };
