// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTrashSimple = {
	"name": "trash-simple",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<line x1=\"216\" y1=\"56\" x2=\"40\" y2=\"56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"88\" y1=\"24\" x2=\"168\" y2=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M200,56V208a8,8,0,0,1-8,8H64a8,8,0,0,1-8-8V56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorTrashSimple;
export { phosphorTrashSimple };
