// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTrendUp = {
	"name": "trend-up",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"232 56 136 152 96 112 24 184\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"232 120 232 56 168 56\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorTrendUp;
export { phosphorTrendUp };
