// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorTrolleySuitcase = {
	"name": "trolley-suitcase",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"72\" cy=\"224\" r=\"16\"/><circle cx=\"216\" cy=\"224\" r=\"16\"/><path d=\"M24,48,45.66,69.66A8,8,0,0,1,48,75.31V184\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"32\" y1=\"184\" x2=\"240\" y2=\"184\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M128,64V40a8,8,0,0,1,8-8h32a8,8,0,0,1,8,8V64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorTrolleySuitcase;
export { phosphorTrolleySuitcase };
