// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorUnion = {
	"name": "union",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M200,64v80a72,72,0,0,1-144,0V64\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorUnion;
export { phosphorUnion };
