// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorUserCheck = {
	"name": "user-check",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<circle cx=\"108\" cy=\"100\" r=\"60\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><path d=\"M24,200c20.55-24.45,49.56-40,84-40s63.45,15.55,84,40\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><polyline points=\"200 144 216 160 248 128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorUserCheck;
export { phosphorUserCheck };
