// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorWaveSine = {
	"name": "wave-sine",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<path d=\"M24,128c104-221.7,104,221.7,208,0\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorWaveSine;
export { phosphorWaveSine };
