// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorWaveSquare = {
	"name": "wave-square",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polyline points=\"232 128 232 184 128 184 128 72 24 72 24 128\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorWaveSquare;
export { phosphorWaveSquare };
