// Generated by scripts/generate-icons.js. Do not edit by hand.
import type { IconData } from '../types.js';

const phosphorXLogo = {
	"name": "x-logo",
	"set": "phosphor",
	"viewBox": "0 0 256 256",
	"body": "<polygon points=\"48 40 96 40 208 216 160 216 48 40\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"113.88\" y1=\"143.53\" x2=\"48\" y2=\"216\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/><line x1=\"208\" y1=\"40\" x2=\"142.12\" y2=\"112.47\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"16\"/>"
} as const satisfies IconData;

export default phosphorXLogo;
export { phosphorXLogo };
