import { createDocsEntries, createDocsLoader } from '@docs-kit/sveltekit';
import { manifest, pageImporters } from 'virtual:docs-kit/manifest';

export const prerender = true;

export const entries = createDocsEntries({ manifest, collection: 'default' });
export const load = createDocsLoader({
	manifest,
	pageImporters,
	collection: 'default',
	site: { title: 'Standalone Docs', description: 'Generated by @docs-kit/create.' }
});
