// The ai-elements registry — source of truth for the AI-elements docs section and port
// tracking. Kept SEPARATE from registry.ts (the core shadcn port) so the two progress
// counters never mix. GENERATED by scripts/ai-elements-plan.mjs — do not hand-edit entries;
// change status by editing the generator's inputs, or flip a single 'status' as you port.

export type AiCategory = 'Conversation' | 'Reasoning' | 'Content' | 'Controls' | 'Canvas';
export type AiTier = 'light' | 'medium' | 'heavy';
export type Status = 'ready' | 'planned';

export type AiComponentEntry = {
	slug: string;
	name: string;
	category: AiCategory;
	tier: AiTier;
	/** Cross-ai-element dependency order. 0 = depends on no other ai-element. */
	wave: number;
	status: Status;
	/** fractalsvelte core components it composes — all already ported. */
	uiDeps: string[];
	/** Other ai-elements it composes — must be ported first (see wave). */
	aiElementDeps: string[];
	/** Runtime packages it imports (already installed). */
	external: string[];
};

export const AI_COMPONENTS: AiComponentEntry[] = [
	{
		slug: 'action',
		name: 'Action',
		category: 'Controls',
		tier: 'light',
		wave: 0,
		status: 'ready',
		uiDeps: ['button', 'tooltip'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'artifact',
		name: 'Artifact',
		category: 'Content',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['button', 'tooltip'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'chain-of-thought',
		name: 'Chain Of Thought',
		category: 'Reasoning',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['badge', 'collapsible'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'checkpoint',
		name: 'Checkpoint',
		category: 'Controls',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['button', 'separator', 'tooltip'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'confirmation',
		name: 'Confirmation',
		category: 'Controls',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['alert', 'button'],
		aiElementDeps: [],
		external: ['runed']
	},
	{
		slug: 'context',
		name: 'Context',
		category: 'Controls',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['button', 'hover-card', 'progress'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'conversation',
		name: 'Conversation',
		category: 'Conversation',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['button'],
		aiElementDeps: [],
		external: ['runed']
	},
	{
		slug: 'copy-button',
		name: 'Copy Button',
		category: 'Controls',
		tier: 'light',
		wave: 0,
		status: 'ready',
		uiDeps: ['button'],
		aiElementDeps: [],
		external: ['bits-ui']
	},
	{
		slug: 'image',
		name: 'Image',
		category: 'Content',
		tier: 'light',
		wave: 0,
		status: 'ready',
		uiDeps: ['button'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'inline-citation',
		name: 'Inline Citation',
		category: 'Content',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['badge', 'carousel', 'hover-card'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'loader',
		name: 'Loader',
		category: 'Controls',
		tier: 'light',
		wave: 0,
		status: 'ready',
		uiDeps: [],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'message',
		name: 'Message',
		category: 'Conversation',
		tier: 'heavy',
		wave: 0,
		status: 'ready',
		uiDeps: ['button', 'button-group', 'dialog', 'tooltip'],
		aiElementDeps: [],
		external: ['@shikijs/themes', 'mode-watcher', 'streamdown-svelte']
	},
	{
		slug: 'model-selector',
		name: 'Model Selector',
		category: 'Controls',
		tier: 'heavy',
		wave: 0,
		status: 'ready',
		uiDeps: ['command', 'dialog'],
		aiElementDeps: [],
		external: ['bits-ui']
	},
	{
		slug: 'open-in-chat',
		name: 'Open In Chat',
		category: 'Controls',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['button', 'dropdown-menu'],
		aiElementDeps: [],
		external: ['runed']
	},
	{
		slug: 'prompt-input',
		name: 'Prompt Input',
		category: 'Conversation',
		tier: 'heavy',
		wave: 0,
		status: 'ready',
		uiDeps: ['aspect-ratio', 'button', 'dialog', 'dropdown-menu', 'textarea', 'tooltip'],
		aiElementDeps: [],
		external: ['ai', 'runed']
	},
	{
		slug: 'queue',
		name: 'Queue',
		category: 'Conversation',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['button', 'collapsible', 'scroll-area'],
		aiElementDeps: [],
		external: ['bits-ui']
	},
	{
		slug: 'response',
		name: 'Response',
		category: 'Conversation',
		tier: 'heavy',
		wave: 0,
		status: 'ready',
		uiDeps: [],
		aiElementDeps: [],
		external: ['@shikijs/themes', 'mode-watcher', 'streamdown-svelte']
	},
	{
		slug: 'shimmer',
		name: 'Shimmer',
		category: 'Controls',
		tier: 'light',
		wave: 0,
		status: 'ready',
		uiDeps: [],
		aiElementDeps: [],
		external: ['runed']
	},
	{
		slug: 'sources',
		name: 'Sources',
		category: 'Content',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['collapsible'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'suggestion',
		name: 'Suggestion',
		category: 'Conversation',
		tier: 'light',
		wave: 0,
		status: 'ready',
		uiDeps: ['button', 'scroll-area'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'task',
		name: 'Task',
		category: 'Reasoning',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['collapsible'],
		aiElementDeps: [],
		external: ['bits-ui']
	},
	{
		slug: 'web-preview',
		name: 'Web Preview',
		category: 'Content',
		tier: 'medium',
		wave: 0,
		status: 'ready',
		uiDeps: ['button', 'collapsible', 'tooltip'],
		aiElementDeps: [],
		external: []
	},
	{
		slug: 'code',
		name: 'Code',
		category: 'Content',
		tier: 'heavy',
		wave: 1,
		status: 'ready',
		uiDeps: ['button'],
		aiElementDeps: ['copy-button'],
		external: ['bits-ui', 'dompurify', 'runed', 'shiki']
	},
	{
		slug: 'plan',
		name: 'Plan',
		category: 'Reasoning',
		tier: 'medium',
		wave: 1,
		status: 'ready',
		uiDeps: ['button', 'card', 'collapsible'],
		aiElementDeps: ['shimmer'],
		external: ['bits-ui']
	},
	{
		slug: 'reasoning',
		name: 'Reasoning',
		category: 'Reasoning',
		tier: 'medium',
		wave: 1,
		status: 'ready',
		uiDeps: ['collapsible'],
		aiElementDeps: ['response'],
		external: ['runed']
	},
	{
		slug: 'tool',
		name: 'Tool',
		category: 'Reasoning',
		tier: 'medium',
		wave: 2,
		status: 'ready',
		uiDeps: ['badge', 'collapsible'],
		aiElementDeps: ['code'],
		external: ['runed']
	}
];

export const AI_CATEGORY_ORDER: AiCategory[] = ['Conversation', 'Reasoning', 'Content', 'Controls', 'Canvas'];

export const aiByCategory = (entries = AI_COMPONENTS) =>
	AI_CATEGORY_ORDER.map((category) => ({
		category,
		items: entries.filter((c) => c.category === category).sort((a, b) => a.name.localeCompare(b.name))
	})).filter((g) => g.items.length > 0);

export const getAiComponent = (slug: string) => AI_COMPONENTS.find((c) => c.slug === slug);

export const aiProgress = () => ({
	aiReady: AI_COMPONENTS.filter((c) => c.status === 'ready').length,
	aiTotal: AI_COMPONENTS.length
});
