import type { DesignNode, TextNode } from "$lib/domain";
import type { ResolvedNode } from "./types";
import { needsInlineSvg, generateInlineSvg } from "./style-mapper";

function htmlEscape(text: string): string {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

function indent(depth: number): string {
	return "\t".repeat(depth);
}

function selfClosingTag(element: string, attrs: Record<string, string>, depth: number): string {
	const parts = [`<${element}`];
	for (const [key, value] of Object.entries(attrs)) {
		if (value !== undefined && value !== "") {
			parts.push(` ${key}="${htmlEscape(value)}"`);
		}
	}
	parts.push(" />");
	return `${indent(depth)}${parts.join("")}`;
}

function openTag(element: string, attrs: Record<string, string>, depth: number): string {
	const parts = [`<${element}`];
	for (const [key, value] of Object.entries(attrs)) {
		if (value !== undefined && value !== "") {
			parts.push(` ${key}="${htmlEscape(value)}"`);
		}
	}
	parts.push(">");
	return `${indent(depth)}${parts.join("")}`;
}

function closeTag(element: string, depth: number): string {
	return `${indent(depth)}</${element}>`;
}

function buildAttrs(resolved: ResolvedNode, isRoot: boolean): Record<string, string> {
	const attrs: Record<string, string> = { class: resolved.className };

	if (resolved.node.type === "image") {
		const img = resolved.node as any;
		attrs.src = img.assetId ? `assets/${img.assetId}.png` : "";
		attrs.alt = resolved.node.name || "Image";
	}

	return attrs;
}

export function emitSvelteMarkup(
	resolvedRoots: ResolvedNode[],
	options: { componentName?: string } = {}
): string {
	const lines: string[] = [];

	for (const root of resolvedRoots) {
		emitNode(root, 0, true, lines);
	}

	return lines.join("\n");
}

function emitNode(
	resolved: ResolvedNode,
	depth: number,
	isRoot: boolean,
	lines: string[]
): void {
	const { node, className, children, inlineSvg } = resolved;
	const element = resolved.element;

	// SVG shapes: render inline SVG inside a wrapper div
	if (needsInlineSvg(node) && inlineSvg) {
		lines.push(`${indent(depth)}<div class="${className}">`);
		lines.push(`${indent(depth + 1)}{@html \`${escapeBacktick(inlineSvg)}\`}`);
		lines.push(`${indent(depth)}</div>`);
		return;
	}

	// Image node
	if (node.type === "image") {
		const attrs = buildAttrs(resolved, isRoot);
		lines.push(selfClosingTag(element, attrs, depth));
		return;
	}

	// Text node
	if (node.type === "text") {
		const textNode = node as TextNode;
		const attrs = buildAttrs(resolved, isRoot);
		const text = textNode.text;
		if (text.includes("\n")) {
			// Multi-line text: use tspan-like approach or just preserve newlines
			lines.push(`${openTag(element, attrs, depth)}${htmlEscape(text)}${closeTag(element, depth)}`);
		} else {
			lines.push(`${openTag(element, attrs, depth)}${htmlEscape(text)}${closeTag(element, depth)}`);
		}
		return;
	}

	// Container or shape node with children
	const attrs = buildAttrs(resolved, isRoot);

	if (children.length === 0) {
		// Self-closing if no children
		if (element === "img") {
			lines.push(selfClosingTag(element, attrs, depth));
		} else {
			lines.push(`${openTag(element, attrs, depth)}${closeTag(element, depth)}`);
		}
		return;
	}

	// Open tag
	lines.push(openTag(element, attrs, depth));

	// Children
	for (const child of children) {
		emitNode(child, depth + 1, false, lines);
	}

	// Close tag
	lines.push(closeTag(element, depth));
}

function escapeBacktick(s: string): string {
	return s.replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

export function emitSvelteComponent(
	resolvedRoots: ResolvedNode[],
	options: {
		componentName?: string;
		styleContent?: string;
	} = {}
): string {
	const { componentName = "ExportedComponent", styleContent = "" } = options;
	const parts: string[] = [];

	// Script block (empty for now, but provides the Svelte 5 structure)
	parts.push("<script lang=\"ts\">");
	parts.push("\t// Generated by Figmaboy export");
	parts.push("</script>");
	parts.push("");

	// Markup
	parts.push("<!-- Generated by Figmaboy -->");
	for (const root of resolvedRoots) {
		emitNode(root, 0, true, parts);
	}
	parts.push("");

	// Style block
	if (styleContent) {
		parts.push("<style lang=\"sass\">");
		parts.push(styleContent);
		parts.push("</style>");
	}

	return parts.join("\n");
}

export function emitHtmlOutput(
	resolvedRoots: ResolvedNode[],
	cssContent: string
): { html: string; css: string } {
	const lines: string[] = [];

	lines.push("<!DOCTYPE html>");
	lines.push("<html lang=\"en\">");
	lines.push("<head>");
	lines.push("\t<meta charset=\"UTF-8\" />");
	lines.push("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />");
	lines.push("\t<title>Exported Design</title>");
	lines.push("\t<link rel=\"stylesheet\" href=\"styles.css\" />");
	lines.push("</head>");
	lines.push("<body>");

	for (const root of resolvedRoots) {
		emitHtmlNode(root, 1, lines);
	}

	lines.push("</body>");
	lines.push("</html>");

	return { html: lines.join("\n"), css: cssContent };
}

function emitHtmlNode(resolved: ResolvedNode, depth: number, lines: string[]): void {
	const { node, className, children, inlineSvg, element } = resolved;

	if (needsInlineSvg(node) && inlineSvg) {
		lines.push(`${indent(depth)}<div class="${className}">`);
		lines.push(`${indent(depth + 1)}${inlineSvg}`);
		lines.push(`${indent(depth)}</div>`);
		return;
	}

	if (node.type === "image") {
		const attrs = buildAttrs(resolved, false);
		lines.push(selfClosingTag(element, attrs, depth));
		return;
	}

	if (node.type === "text") {
		const textNode = node as TextNode;
		const attrs = buildAttrs(resolved, false);
		lines.push(`${openTag(element, attrs, depth)}${htmlEscape(textNode.text)}${closeTag(element, depth)}`);
		return;
	}

	const attrs = buildAttrs(resolved, false);

	if (children.length === 0) {
		if (element === "img") {
			lines.push(selfClosingTag(element, attrs, depth));
		} else {
			lines.push(`${openTag(element, attrs, depth)}${closeTag(element, depth)}`);
		}
		return;
	}

	lines.push(openTag(element, attrs, depth));
	for (const child of children) {
		emitHtmlNode(child, depth + 1, lines);
	}
	lines.push(closeTag(element, depth));
}
