// Emit an indented-SASS palette file from the frozen shadcn token data.
//
//   node scripts/gen-palette.mjs neutral            -> src/lib/styles/_tokens.sass  (:root + .dark)
//   node scripts/gen-palette.mjs violet --class     -> src/lib/styles/themes/_violet.sass
//
// Source data is src/lib/styles/data/palettes.json, frozen from the shadcn registry
// so palettes stay regenerable after shadcn-registry/ is deleted.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const { palettes } = JSON.parse(readFileSync(`${ROOT}/src/lib/styles/data/palettes.json`, "utf8"));

const [name = "neutral", ...flags] = process.argv.slice(2);
const asClass = flags.includes("--class");

const palette = palettes[name];
if (!palette) {
	console.error(`unknown palette "${name}" — available: ${Object.keys(palettes).join(", ")}`);
	process.exit(1);
}

const TAB = "\t";
const decls = (tokens, indent) =>
	Object.entries(tokens)
		.map(([token, value]) => `${TAB.repeat(indent)}--${token}: ${value}`)
		.join("\n");

const lightSel = asClass ? `.theme-${name}` : ":root";
const darkSel = asClass ? `.theme-${name}.dark` : ".dark";

const out = [
	`// Generated by scripts/gen-palette.mjs — palette "${name}". Do not edit by hand;`,
	`// re-run the generator instead. Token names mirror shadcn so upstream diffs stay legible.`,
	``,
	lightSel,
	decls(palette.light, 1),
	``,
	darkSel,
	decls(palette.dark, 1),
	``,
].join("\n");

const dest = asClass
	? `${ROOT}/src/lib/styles/themes/_${name}.sass`
	: `${ROOT}/src/lib/styles/_tokens.sass`;

mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, out);

const n = Object.keys(palette.light).length;
console.log(`wrote ${dest.replace(ROOT + "/", "")} — ${n} tokens (${lightSel} / ${darkSel})`);