#!/usr/bin/env python3
"""Style-system audit for FractalEngine Studio.

Cross-references definitions in .sass files (CSS custom properties, SASS
variables, mixins, class selectors) against usage in .svelte/.ts/.html source,
and flags: unused tokens/classes, dead token references, retired ADR-031
classes, hardcoded-value violations, and duplicate class definitions.

Read-only: produces a report, modifies nothing.
"""
import re
import glob
from collections import defaultdict

SASS = sorted(
    glob.glob("src/lib/styles/**/*.sass", recursive=True)
    + glob.glob("src/lib/modules/*/styles/*.sass")
)
CODE = sorted(
    f
    for f in glob.glob("src/**/*", recursive=True)
    if f.endswith((".svelte", ".ts", ".js", ".html"))
)
TOKENS_FILE = "src/lib/styles/_tokens.sass"

cssvars = defaultdict(list)   # --name -> [(file, line)]
sassvars = defaultdict(list)  # $name -> [(file, line)]
mixins = defaultdict(list)    # name -> [(file, line)]
classes = defaultdict(list)   # name -> [(file, line)]

def strip_comment(line: str) -> str:
    # drop trailing // comments (good enough for this codebase)
    idx = line.find("//")
    return line if idx < 0 else line[:idx]

for f in SASS:
    for i, raw in enumerate(open(f, encoding="utf-8"), 1):
        line = strip_comment(raw)
        s = line.strip()
        if not s:
            continue
        m = re.match(r"^(--[\w-]+)\s*:", s)
        if m:
            cssvars[m.group(1)].append((f, i))
        m = re.match(r"^(\$[\w-]+)\s*:", s)
        if m:
            sassvars[m.group(1)].append((f, i))
        m = re.match(r"^=([\w-]+)", s)
        if m:
            mixins[m.group(1)].append((f, i))
        if re.match(r"^\.", s) or re.match(r"^&\.", s):
            for cname in re.findall(r"\.([a-zA-Z_][\w-]*)", s):
                classes[cname].append((f, i))

# ---------- usage corpus ----------
file_text = {}
for f in SASS + CODE:
    file_text[f] = open(f, encoding="utf-8").read()

def count_refs(name: str, exclude_defs=True):
    """Occurrences of token name outside its own definition lines."""
    total = 0
    per_file = {}
    pat = re.compile(re.escape(name) + r"(?![\w-])")
    for f, text in file_text.items():
        n = len(pat.findall(text))
        if n:
            per_file[f] = n
            total += n
    if exclude_defs:
        defs = cssvars.get(name) or sassvars.get(name) or []
        for f, _ln in defs:
            # each definition line contains exactly one occurrence of the name
            total -= sum(1 for _f, _ in defs if _f == f)
    return max(total, 0), per_file

# ---------- CSS var usage ----------
unused_vars, single_use_vars, low_use_vars = [], [], []
var_ref_counts = {}
for name, defs in sorted(cssvars.items()):
    refs, per_file = count_refs(name)
    var_ref_counts[name] = refs
    if refs == 0:
        unused_vars.append((name, defs))
    elif refs == 1:
        single_use_vars.append((name, defs, per_file))
    elif refs == 2:
        low_use_vars.append((name, defs, per_file))

# tokens referenced but never defined
defined_var_names = set(cssvars)
# dynamic --pxN vars are JIT-generated by fractals-styler
referenced = set()
for f, text in file_text.items():
    for m in re.finditer(r"var\(\s*(--[\w-]+)", text):
        referenced.add(m.group(1))
    for m in re.finditer(r"style:(--[\w-]+)", text):
        referenced.add(m.group(1))
    for m in re.finditer(r"setProperty\(\s*['\"](--[\w-]+)", text):
        referenced.add(m.group(1))
undefined_refs = {
    v for v in referenced if v not in defined_var_names and not re.fullmatch(r"--px\d+", v)
}

# ---------- SASS var / mixin usage ----------
unused_sassvars = []
for name, defs in sorted(sassvars.items()):
    refs, _ = count_refs(name)
    if refs == 0:
        unused_sassvars.append((name, defs))

unused_mixins = []
for name, defs in sorted(mixins.items()):
    pat = re.compile(r"\+" + re.escape(name) + r"(?![\w-])")
    refs = sum(len(pat.findall(t)) for t in file_text.values())
    if refs == 0:
        unused_mixins.append((name, defs))

# ---------- class usage ----------
BREAKPOINT_SUFFIX = re.compile(r"-(xs|sm|bs|lg|xl)$")
JIT_NUMERIC = re.compile(
    r"^(gap|cgap|rgap|pad|padtop|padbot|padleft|padright|margin|margintop|"
    r"marginbot|marginleft|marginright|height|width)\d+$"
)
# external library class prefixes we expect to be undefined in our .sass
EXTERNAL_PREFIXES = ("cm-", "katex", "svelte-", "tippy", "hljs", "mermaid")

used_classes = set()          # base class names seen in markup/TS
markup_tokens = defaultdict(list)  # token -> [files] for undefined detection

def add_token(tok: str, f: str):
    if not re.fullmatch(r"[a-zA-Z_][\w-]*", tok):
        return
    markup_tokens[tok].append(f)
    base = BREAKPOINT_SUFFIX.sub("", tok)
    used_classes.add(tok)
    used_classes.add(base)

for f in CODE:
    text = file_text[f]
    # class="..." / class='...'
    for m in re.finditer(r"class\s*=\s*\"([^\"]*)\"", text):
        body = re.sub(r"\{[^}]*\}", " ", m.group(1))
        for tok in body.split():
            add_token(tok, f)
    for m in re.finditer(r"class\s*=\s*'([^']*)'", text):
        body = re.sub(r"\{[^}]*\}", " ", m.group(1))
        for tok in body.split():
            add_token(tok, f)
    # class:foo={...}
    for m in re.finditer(r"class:([\w-]+)", text):
        add_token(m.group(1), f)
    # classList.add/toggle/remove('foo')
    for m in re.finditer(r"classList\.\w+\(\s*['\"]([\w-]+)['\"]", text):
        add_token(m.group(1), f)
    # exact quoted strings anywhere (TS registries, object values)
    for m in re.finditer(r"['\"`]([a-zA-Z_][\w-]*)['\"`]", text):
        tok = m.group(1)
        if tok in classes or BREAKPOINT_SUFFIX.sub("", tok) in classes:
            add_token(tok, f)

# dynamically-constructed class prefixes, e.g. `icon-${size}` or 'note-row-' + x
dynamic_fragments = set()
for f in CODE:
    for m in re.finditer(r"['\"`]([a-zA-Z][\w-]*-)\$?\{?['\"`]?\s*[+}]", file_text[f]):
        dynamic_fragments.add(m.group(1))
    for m in re.finditer(r"`[a-zA-Z][\w-]*-\$\{", file_text[f]):
        dynamic_fragments.add(m.group(0)[1:-2] + "-")

dead_classes = []
for cname, defs in sorted(classes.items()):
    if cname in used_classes:
        continue
    if any(cname.startswith(frag) or frag.startswith(cname + "-") for frag in dynamic_fragments):
        continue  # possibly constructed dynamically — exclude, verify manually
    dead_classes.append((cname, defs))

undefined_markup = []
for tok, files in sorted(markup_tokens.items()):
    base = BREAKPOINT_SUFFIX.sub("", tok)
    if tok in classes or base in classes:
        continue
    if JIT_NUMERIC.match(BREAKPOINT_SUFFIX.sub("", tok)):
        continue
    if tok.startswith(EXTERNAL_PREFIXES):
        continue
    undefined_markup.append((tok, sorted(set(files))))

# ---------- retired ADR-031 classes ----------
RETIRED = [
    "icon-button", "strip-button", "panel-button-std", "panel-text-label",
    "panel-text-std", "panel-text-bs", "panel-text-std-accent",
    "panel-text-std-muted", "panel-text-desc", "panel-text-alive",
    "panel-text-small", "sidebar-tab-pill", "ai-sidebar-tab", "ai-tab-btn",
    "file-title", "file-desc",
]
retired_hits = []
for r in RETIRED:
    pat = re.compile(r"(?<![\w-])" + re.escape(r) + r"(?![\w-])")
    for f, text in file_text.items():
        for i, line in enumerate(text.splitlines(), 1):
            if pat.search(line):
                retired_hits.append((r, f, i, line.strip()[:100]))
# inspector-icon-btn may only exist layered WITH btn-icon
for f, text in file_text.items():
    if "inspector-icon-btn" in text:
        for i, line in enumerate(text.splitlines(), 1):
            if "inspector-icon-btn" in line and "btn-icon" not in line and f.endswith(".svelte"):
                retired_hits.append(("inspector-icon-btn(without btn-icon)", f, i, line.strip()[:100]))

# ---------- hardcoded values in .sass ----------
VIOLATION_PATTERNS = [
    ("hex-color", re.compile(r"#[0-9a-fA-F]{3,8}\b")),
    ("rgba-literal", re.compile(r"\brgba?\(")),
    ("font-size-px", re.compile(r"font-size:\s*[\d.]+px")),
    ("radius-px", re.compile(r"border-radius:\s*[\d.]+px")),
    ("shadow-px", re.compile(r"(?:box-shadow|text-shadow):[^/]*\d+px")),
    ("spacing-px", re.compile(r"(?:^|\s)(?:padding|padding-top|padding-bottom|padding-left|padding-right|margin|margin-top|margin-bottom|margin-left|margin-right|gap|row-gap|column-gap|top|left|right|bottom|width|height|min-width|max-width|min-height|max-height):\s*[\d.]+px")),
]
violations = defaultdict(list)
for f in SASS:
    if f == TOKENS_FILE:
        continue
    for i, raw in enumerate(open(f, encoding="utf-8"), 1):
        line = strip_comment(raw)
        if not line.strip():
            continue
        for kind, pat in VIOLATION_PATTERNS:
            if pat.search(line):
                violations[kind].append((f, i, line.strip()[:110]))

# ---------- duplicate class definitions across files ----------
dup_classes = {
    c: sorted({f for f, _ in defs})
    for c, defs in classes.items()
    if len({f for f, _ in defs}) > 1
}

# ---------- style blocks / inline styles in svelte ----------
style_blocks = []
inline_styles = []
for f in CODE:
    if not f.endswith(".svelte"):
        continue
    text = file_text[f]
    for m in re.finditer(r"<style", text):
        style_blocks.append(f)
    for m in re.finditer(r'style\s*=\s*"([^"]*)"', text):
        body = m.group(1)
        if "{" not in body and body.strip():
            ln = text[: m.start()].count("\n") + 1
            inline_styles.append((f, ln, body.strip()[:90]))

# ---------- report ----------
def fmt_defs(defs):
    return ", ".join(f"{f}:{i}" for f, i in defs[:4]) + (" …" if len(defs) > 4 else "")

out = []
A = out.append
A("# Style System Audit\n")
A(f"Scanned {len(SASS)} .sass files, {len(CODE)} code files.\n")
A(f"Defined: {len(cssvars)} CSS vars · {len(sassvars)} SASS vars · {len(mixins)} mixins · {len(classes)} class names\n")

A("\n## 1. Unused CSS custom properties (0 references)\n")
for name, defs in unused_vars:
    A(f"- `{name}` — defined {fmt_defs(defs)}")
A(f"\n**{len(unused_vars)} unused**\n")

A("\n## 2. Single-use CSS custom properties\n")
for name, defs, per in single_use_vars:
    use = [f for f in per if f != TOKENS_FILE] or list(per)
    A(f"- `{name}` — def {fmt_defs(defs)} · sole use {', '.join(use[:2])}")
A(f"\n**{len(single_use_vars)} single-use**\n")

A("\n## 3. Referenced but never defined (dead references)\n")
for v in sorted(undefined_refs):
    sites = [f for f, t in file_text.items() if v in t]
    A(f"- `{v}` — referenced in {', '.join(sites[:4])}")
A(f"\n**{len(undefined_refs)} dead references**\n")

A("\n## 4. Unused SASS variables / mixins\n")
for name, defs in unused_sassvars:
    A(f"- `{name}` — defined {fmt_defs(defs)}")
for name, defs in unused_mixins:
    A(f"- mixin `={name}` — defined {fmt_defs(defs)}")
A(f"\n**{len(unused_sassvars)} unused SASS vars · {len(unused_mixins)} unused mixins**\n")

A("\n## 5. Classes defined but never used in markup/TS\n")
A("(verify dynamically-constructed names before deleting)\n")
for cname, defs in dead_classes:
    A(f"- `.{cname}` — {fmt_defs(defs)}")
A(f"\n**{len(dead_classes)} candidates**\n")
A("\nDynamic construction fragments detected (excluded from dead list): "
  + (", ".join(sorted(dynamic_fragments)) or "none") + "\n")

A("\n## 6. Classes used in markup but not defined in .sass (and not JIT/external)\n")
for tok, files in undefined_markup:
    A(f"- `.{tok}` — used in {', '.join(files[:3])}{' …' if len(files) > 3 else ''}")
A(f"\n**{len(undefined_markup)} candidates**\n")

A("\n## 7. Retired ADR-031 class occurrences\n")
for r, f, i, line in retired_hits:
    A(f"- `{r}` — {f}:{i} — `{line}`")
A(f"\n**{len(retired_hits)} occurrences**\n")

A("\n## 8. Hardcoded values in .sass (tokens-only rule)\n")
for kind in ["hex-color", "rgba-literal", "font-size-px", "radius-px", "shadow-px", "spacing-px"]:
    hits = violations.get(kind, [])
    A(f"\n### {kind} ({len(hits)})\n")
    for f, i, line in hits[:60]:
        A(f"- {f}:{i} — `{line}`")
    if len(hits) > 60:
        A(f"- … {len(hits) - 60} more")

A("\n## 9. Class names defined in more than one .sass file\n")
for c, files in sorted(dup_classes.items()):
    A(f"- `.{c}` — {', '.join(files)}")
A(f"\n**{len(dup_classes)} duplicated names**\n")

A("\n## 10. <style> blocks in .svelte / static inline styles\n")
A(f"- `<style>` blocks: {len(style_blocks)} — {sorted(set(style_blocks))[:10]}")
A(f"- static `style=\"...\"` attributes: {len(inline_styles)}")
for f, ln, body in inline_styles[:30]:
    A(f"  - {f}:{ln} — `{body}`")

report = "\n".join(out) + "\n"
open("style-audit-report.md", "w", encoding="utf-8").write(report)

# compact stdout summary
print(f"CSS vars: {len(cssvars)} defined | {len(unused_vars)} unused | {len(single_use_vars)} single-use | {len(undefined_refs)} dead refs")
print(f"SASS vars: {len(sassvars)} defined | {len(unused_sassvars)} unused | mixins: {len(mixins)} defined | {len(unused_mixins)} unused")
print(f"Classes: {len(classes)} defined | {len(dead_classes)} dead candidates | {len(undefined_markup)} undefined-in-markup candidates")
print(f"Retired classes: {len(retired_hits)} occurrences")
print("Violations:", {k: len(v) for k, v in violations.items()})
print(f"Duplicate class names across files: {len(dup_classes)}")
print(f"<style> blocks: {len(set(style_blocks))} | static inline styles: {len(inline_styles)}")
print("Full report: style-audit-report.md")
